-- MySQL Script generated by MySQL Workbench
-- Tue Jul 27 22:03:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_development_groupomania` DEFAULT CHARACTER SET utf8 ;
USE `database_development_groupomania` ;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_development_groupomania`.`USERS` (
  `id` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_development_groupomania`.`Posts` (
  `id` INT NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `user_id` SMALLINT(5) NULL,
  `imageUrl` VARCHAR(255) NULL,
  `content` VARCHAR(45) NULL,
  `USERS_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Posts_USERS1_idx` (`USERS_id` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_USERS1`
    FOREIGN KEY (`USERS_id`)
    REFERENCES `database_development_groupomania`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_development_groupomania`.`COMMENTS` (
  `id` INT NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `USERS_id` INT NOT NULL,
  `Posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_COMMENTS_USERS1_idx` (`USERS_id` ASC) VISIBLE,
  INDEX `fk_COMMENTS_Posts1_idx` (`Posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMMENTS_USERS1`
    FOREIGN KEY (`USERS_id`)
    REFERENCES `database_development_groupomania`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENTS_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `database_development_groupomania`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
